apiVersion: v1 
kind: Service 
metadata: 
  name: flask-app-service 
spec: 
  type: NodePort 
  selector: 
    app: To-do
  ports: 
  - protocol: TCP 
    port: 5000 
    targetPort: 5000 
    nodePort: 30001